var TopMenuOffsetX=0,TopMenuOffsetY=0,LeftMenuOffsetX=0,LeftMenuOffsetY=0,LanguageMenuOffsetX=0,LanguageMenuOffsetY=0;
function DIY_Browser(){d=document;this.agent=navigator.userAgent.toLowerCase();this.major=parseInt(navigator.appVersion);this.dom=d.getElementById?1:0;this.ns4up=(this.ns=d.layers)&&this.major>=4;this.ns6=this.dom&&navigator.appName=="Netscape";this.op=this.agent.indexOf("opera")!=-1&&this.major<7;this.opera5=this.agent.indexOf("Opera 5")>-1;this.ie4=(this.ie=d.all)&&!this.dom?1:0;this.ie4up=this.ie&&this.major>=4;this.ie5=d.all&&this.dom;this.ie6=this.agent.indexOf("msie 6")>-1&&this.dom&&!this.opera5?
1:0;this.win=this.agent.indexOf("win")!=-1||this.agent.indexOf("16bit")!=-1;this.mac=this.agent.indexOf("mac")!=-1}var oBw=new DIY_Browser;function getH(a){var b=0;return oBw.ns?b=a.height?a.height:a.clip.height:b=oBw.op?a.style.pixelHeight:a.offsetHeight}function setH(a,b){if(oBw.ns){if(a.clip)a.clip.bottom=b}else oBw.op?a.style.pixelHeight=b:a.style.height=b}function getW(a){var b=0;return oBw.ns?b=a.width?a.width:a.clip.width:b=oBw.op?a.style.pixelWidth:a.offsetWidth}
function setW(a,b){if(oBw.ns){if(a.clip)a.clip.right=b}else oBw.op?a.style.pixelWidth=b:a.style.width=b}function getX(a){return oBw.ns?a.left:oBw.op?a.style.pixelLeft:a.offsetLeft}function setX(a,b){oBw.ns?a.left=b:oBw.op?a.style.pixelLeft=b:a.style.left=b}function getY(a){return oBw.ns?a.top:oBw.op?a.style.pixelTop:a.offsetTop}function setY(a,b){oBw.ie||oBw.dom?a.style.top=b:oBw.ns?a.top=b:a.style.pixelTop=b}
function getPageX(a){if(oBw.ns)var b=a.pageX?a.pageX:a.x;else if(oBw.op)for(b=0;eval(a);)b+=a.stylo.pixelLeft,e=a.offsetParent;else for(b=0;eval(a);)b+=a.offsetLeft,a=a.offsetParent;return b}function getPageY(a){if(oBw.ns)var b=a.pageY?a.pageY:a.y;else if(oBw.op)for(b=0;eval(a);)b+=a.stylo.pixelTop,a=a.offsetParent;else for(b=0;eval(a);)b+=a.offsetTop,a=a.offsetParent;return b}
function mpageX(a){var b=0;do if(a.style.position=="absolute")return b+a.offsetLeft;else b+=a.offsetLeft,a.offsetParent&&a.offsetParent.tagName=="TABLE"&&parseInt(a.offsetParent.border)>0&&(b+=1);while(a=a.offsetParent);return b}function mpageY(a){var b=0;do if(a.style.position=="absolute")return b+a.offsetTop;else b+=a.offsetTop,a.offsetParent&&a.offsetParent.tagName=="TABLE"&&parseInt(a.offsetParent.border)>0&&(b+=1);while(a=a.offsetParent);return b}
function _MyMenuItemOut(){var a=_MyMenuItemOut.arguments;_MyShowHideLayers(a[0],a[1],a[2],a[3],a[4],a[5])}function _MyMenuItemOver(){var a=_MyMenuItemOver.arguments;_MyShowHideLayers(a[0],a[1],a[2],a[3],a[4],a[5])}
function _MyInitDivPosition(){var a=_MyInitDivPosition.arguments,b=getObject(a[0]),c=getObject(a[1]),c=c.style;if(a[2]=="MAIN_TOP")c.top=getPageY(b)+b.offsetHeight+TopMenuOffsetY,c.left=getPageX(b)+TopMenuOffsetX;else if(a[2]=="MAIN_LEFT")c.top=getPageY(b)+LeftMenuOffsetY,c.left=getPageX(b)+b.offsetWidth+LeftMenuOffsetX;else if(a[2]=="LANGUAGE")c.top=getPageY(b)+b.offsetHeight+LanguageMenuOffsetY,c.left=getPageX(b)+LanguageMenuOffsetX}
function _MyShowHideLayers(){var a,b,c;a=_MyShowHideLayers.arguments;if((c=getObject(a[0]))!=null){a=a[2];if(c.style)c=c.style,b=a=="show"?"visible":a=="hide"?"hidden":a;c.display="block";c.visibility=b}}
function MyOpenWindowPos(a,b,c,f,g){var h=screen.width-10,j=screen.height-57,k="";g==1?k="top=0, left=0, screenX=0, screenY=0,":g==2?k="top=0, left="+(h-c)+", screenX="+(h-c)+", screenY=0,":g==0?k="":g==3?k="top="+(j-f)+", left=0, screenX=0, screenY="+(j-f)+",":g==5&&(k="top="+(j-f)+", left="+(h-c)+", screenX="+(h-c)+", screenY="+(j-f)+",");openwindow(a,b,c,f,k)}function MyOpenWindow(a,b,c,f,g){openwindow(a,b,c,f,g)}
function openwindow(a,b,c,f,g){yposition=xposition=0;parseInt(navigator.appVersion)>=4&&(c==1?(c=screen.width-10,xposition=0):xposition=(screen.width-c)/2,f==1?(f=screen.height-57,yposition=0):yposition=(screen.height-f)/2-15,yposition<0&&(yposition=0));theproperty="width="+c+", height="+f+", ";g.toLowerCase().indexOf("screenx")==-1&&(theproperty+="screenX="+xposition+", ");g.toLowerCase().indexOf("screenY")==-1&&(theproperty+="screenY="+yposition+", ");g.toLowerCase().indexOf("left")==-1&&(theproperty+=
"left="+xposition+", ");g.toLowerCase().indexOf("top")==-1&&(theproperty+="top="+yposition+", ");g.toLowerCase().indexOf("location")==-1&&(theproperty+="location=0, ");g.toLowerCase().indexOf("menubar")==-1&&(theproperty+="menubar=0, ");g.toLowerCase().indexOf("resizable")==-1&&(theproperty+="resizable=0, ");g.toLowerCase().indexOf("scrollbars")==-1&&(theproperty+="scrollbars=1, ");g.toLowerCase().indexOf("status")==-1&&(theproperty+="status=0, ");g.toLowerCase().indexOf("toolbar")==-1&&(theproperty+=
"toolbar=0, ");g.toLowerCase().indexOf("hotkeys")==-1&&(theproperty+="hotkeys=0, ");theproperty=theproperty+", "+g;return window.open(a,b,theproperty)}
function toDate(a,b,c,f){if(a.value=="-1"||b.value=="-1")b.options[0].selected=!0,c.options[0].selected=!0;else{vYear=parseInt(a.options[a.selectedIndex].value);vMonth=parseInt(b.options[b.selectedIndex].value);c.length=1;for(i=0;i<(new Date(vYear,vMonth,0)).getDate();i++)c.options[c.length++].value=c.length-1,c.options[c.length-1].text=c.length-1;if(f>0)c.options[f].selected=!0}}
function isDate(a){if(trim(a)=="")return!1;if(!/^((\d{4})|(\d{2}))-(\d{1,2})-(\d{1,2})$/g.test(a))return!1;a=a.split("-");if(parseInt(a[0],10)<1900)return!1;var b=new Date(a[0],parseInt(a[1],10)-1+"",a[2]);return b.getMonth()==parseInt(a[1],10)-1+""&&b.getDate()==a[2]?!0:!1}function GetCookieVal(a){var b=document.cookie.indexOf(";",a);if(b==-1)b=document.cookie.length;return unescape(document.cookie.substring(a,b))}
function SetCookie(a,b){var c=new Date,f=SetCookie.arguments,g=SetCookie.arguments.length,h=g>2?f[2]:null,j=g>3?f[3]:null,k=g>4?f[4]:null,f=g>5?f[5]:!1;h!=null&&c.setTime(c.getTime()+h*1E3);document.cookie=a+"="+escape(b)+(h==null?"":"; expires="+c.toGMTString())+(j==null?"":"; path="+j)+(k==null?"":"; domain="+k)+(f==!0?"; secure":"")}function DelCookie(a){var b=new Date;b.setTime(b.getTime()-1);var c=GetCookie(a);document.cookie=a+"="+c+"; expires="+b.toGMTString()}
function GetCookie(a){a+="=";for(var b=a.length,c=document.cookie.length,f=0;f<c;){var g=f+b;if(document.cookie.substring(f,g)==a)return GetCookieVal(g);f=document.cookie.indexOf(" ",f)+1;if(f==0)break}return null}
function getObject(a,b){var c,f;b||(b=document);if((c=a.indexOf("?"))>0&&parent.frames.length)b=parent.frames[a.substring(c+1)].document,a=a.substring(0,c);if(!(f=b[a])&&b.all)f=b.all[a];for(c=0;!f&&c<b.forms.length;c++)f=b.forms[c][a];for(c=0;!f&&b.layers&&c<b.layers.length;c++)f=getObject(a,b.layers[c].document);!f&&b.getElementById&&(f=b.getElementById(a));return f}
function convertBytesToSize(a){var b="B",c=a/1024,f=c/1024,g=f/1024,h="0";g>1?(b="Gb",h=MyStr2Float(g,3,"str")):f>1?(b="Mb",h=MyStr2Float(f,3,"str")):c>1?(b="Kb",h=MyStr2Float(c,3,"str")):(b="Bytes",h=MyStr2Float(a,3,"str"));return h+b}function trim(a){regExp1=/^ */;regExp2=/ *$/;return a.replace(regExp1,"").replace(regExp2,"")}function MyWindowClose(){opener=null;window.close()}function MyGetKeyCode(a){var b;if(!a)a=window.event;if(a.keyCode)b=a.keyCode;else if(a.which)b=a.which;return b}
function MyCheckNum(a,b){var c=MyGetKeyCode(b);return(c<45||c>57||c==47)&&c!=45&&c!=9&&c!=8?!1:c==46&&a.value.indexOf(".")>-1?!1:!0}function MyCheckInt(a,b){var c=MyGetKeyCode(b);return(c<48||c>57)&&c!=45&&c!=9&&c!=8?!1:!0}function CheckNum(a){if((window.event.keyCode<45||window.event.keyCode>57||window.event.keyCode==47)&&window.event.keyCode!=45&&window.event.keyCode!=9)window.event.returnValue=!1;if(window.event.keyCode==46&&a.value.indexOf(".")>-1)window.event.returnValue=!1}
function CheckInt(){if((window.event.keyCode<48||window.event.keyCode>57)&&window.event.keyCode!=45&&window.event.keyCode!=9)window.event.returnValue=!1}function MyOnfocusSelect(a){a.type=="text"&&a.select()}function isEmail(a){return RegExp(/^\w+((-\w+)|(\.\w+))*\@[A-Za-z0-9]+((\.|-)[A-Za-z0-9]+)*\.[A-Za-z0-9]+$/).test(a)}function getFullName(a){var b=-1,b=a.lastIndexOf("\\");b==-1&&(b=a.lastIndexOf("/"));return b==-1?a:a.substring(b+1)}
function getName(a){var b=-1,c=-1,b=a.lastIndexOf("\\");b==-1&&(b=a.lastIndexOf("/"));c=a.indexOf(".",b);return c==-1?a.substring(b+1):a.substring(b+1,c)}function getFileExt(a){a=a.substring(a.lastIndexOf(".")+1);return a.toUpperCase()}function MyCheckExt(a,b){var c=getFileExt(a),b=","+b.toUpperCase()+",",f=b.indexOf(","+c+",");return c==""?-1:f==-1?0:1}function getFullPath(a){var b=-1,b=a.lastIndexOf("\\");b==-1&&(b=a.lastIndexOf("/"));return b==-1?"":a.substring(0,b+1)}
function MyClearObject(a){a.value=""}function MyStr2Float(a,b,c){var f=0,g=0,h="1",f=""+a,a="",g=0,f=parseFloat(isNaN(parseFloat(f))?0:f);switch(!0){case b==0:f=Math.round(f);break;case b>0:for(a=0;a<b;a++)h+="0";g=parseInt(h);f=Math.round(f*g)/g;c=="str"&&(a=f.toString(),a+=(a.indexOf(".")!=-1?"":".")+h.substr(1),g=a.indexOf(".")+1+b,f=a.substr(0,g))}return f}function checkFormType(a){return a.length?a[0].type:a.type}
function ClearSelected(a,b){if(a!=null)if(a.length==null){if(b==-1)a.checked=!1}else for(i=0;i<a.length;i++)a[i].checked=b!=-1&&b==i?!0:!1}function SelectedAll(a){if(a!=null)if(a.length==null)a.checked=!0;else for(i=0;i<a.length;i++)a[i].checked=!0}function InverseSelected(a){if(a!=null)if(a.length==null)a.checked=!a.checked;else for(i=0;i<a.length;i++)a[i].checked=!a[i].checked}function FocusOptions(a){a!=null&&(a.length==null?a.focus():a[0].focus())}
function CheckIsSelected(a){var b=!1;if(a!=null)if(a.length==null)a.checked==!0&&(b=!0);else for(var c=0;c<a.length;c++)if(a[c].checked==!0){b=!0;break}return b}function SetSelected(a,b){if(a!=null)if(a.length==null){if(b==0)a.checked=!0}else a[b].checked=!0}function getSelectedValue(a){var b="";if(a!=null)if(a.length==null){if(a.checked==!0)b=a.value}else for(i=0;i<a.length;i++)if(a[i].checked==!0){b=a[i].value;break}return b}
function OperateSelect(a,b){var c;try{c=b.value,b.options[0].selected=!0}catch(f){c=b}if(a)if(a.length==null){if(!a.disabled)switch(c){case "all":a.checked=!0;break;case "invert":a.checked=!a.checked;break;case "none":a.checked=!1}}else for(var g=0;g<a.length;g++)if(!a[g].disabled)switch(c){case "all":a[g].checked=!0;break;case "invert":a[g].checked=!a[g].checked;break;case "none":a[g].checked=!1}}
function OperateSelectCustom(a,b,c,f){var g,h=null;try{g=f.value,f.options[0].selected=!0}catch(j){g=f}if(c)if(c.length==null){if(!c.disabled)switch(h=eval("document."+a+"."+b+c.value),g){case "all":h.checked=!0;break;case "invert":h.checked=!h.checked;break;case "none":h.checked=!1}}else for(f=0;f<c.length;f++)if(!c[f].disabled)switch(h=eval("document."+a+"."+b+c[f].value),g){case "all":h.checked=!0;break;case "invert":h.checked=!h.checked;break;case "none":h.checked=!1}}
function SetSelectItem(a,b){for(var c=0;c<a.options.length;c++)if(a.options[c].value==b){a.options[c].selected=!0;break}}function checkLength(a,b){return a.replace(/[^\x00-\xff]/g,"**").length>b?!0:!1}function getPath(a){if(a){if(window.navigator.userAgent.indexOf("MSIE")>=1)return a.select(),document.selection.createRange().text;else if(window.navigator.userAgent.indexOf("Firefox")>=1&&a.files)return a.files.item(0).getAsDatUrl();return a.value}}
function PreviewPic(a){a=getPath(a);a==""?alert("Please select a image!"):window.open("previewImage.asp?img="+a,"preImg","")}function AddToFavorite(a,b,c){typeof window.sidebar=="object"&&typeof window.sidebar.addPanel=="function"?window.sidebar.addPanel(a,b,c):window.external.AddFavorite(b,a)}function isRegisterUserName(a){return!/^[a-zA-Z]{1}([a-zA-Z0-9_]){5,19}$/.exec(a)?!1:!0}function high(a){theobject=a;highlighting=setInterval("highlightit(theobject)",50)}
function low(a){clearInterval(highlighting);a.filters.alpha.opacity=50}function highlightit(a){a.filters.alpha.opacity<100?a.filters.alpha.opacity+=5:window.highlighting&&clearInterval(highlighting)}function hidDiv(a){a.style.display="none"}function showDiv(a){a.style.display=""}function getRadio(a,b,c,f){var g=c/a,h=f/b,j=Math.min(g,h);c==0&&f==0||j>1?j=1:c==0?j=h<1?h:1:f==0&&(j=g<1?g:1);a*=j;b*=j;return[a,b]}
function AutoResizeImage(a,b,c){typeof c=="string"&&(c=$(c));if(c.src.indexOf("blank.gif")==-1){var f=new Image;f.onload=function(){this.onload=function(){};var g=getRadio(f.width,f.height,a,b);c.width=g[0];c.height=g[1];AlphaImageLoader(c)};f.src=c.src}}
function AutoResizeImage1(a,b,c){var f,g=1;f=!0;var h=getObject(c);h==null&&(f=!1);f&&h.width==0&&(f=!1);var j=0,k=0;if(f)if(k=new Image,k.src=h.src,j=k.width,k=k.height,j==0)window.setTimeout("AutoResizeImage("+a+","+b+",'"+c+"')",500);else{f=a/j;c=b/k;if(a==0)c<1&&(g=c);else if(b==0)f<1&&(g=f);else if(f<1||c<1)g=f<=c?f:c;g<1?(h.width=j*g,h.height=k*g):(h.width=j,h.height=k)}else window.setTimeout("AutoResizeImage("+a+","+b+",'"+c+"')",500)}
function AlphaImageLoader(a){if(is_ie6down){var b=a.src.toUpperCase();if(b.substring(b.length-3,b.length)=="PNG"){var b=a.id?"id='"+a.id+"' ":"",c=a.className?"class='"+a.className+" ' ":" ",f=a.title?"title='"+a.title+"' ":"title='"+a.alt+"' ",g="display:inline-block;"+a.style.cssText;a.align=="left"&&(g="float:left;"+g);a.align=="right"&&(g="float:right;"+g);a.parentElement.href&&(g="cursor:hand;"+g);a.outerHTML='<img src="../images/blank.gif" '+b+c+f+' style="width:'+a.width+"px; height:"+a.height+
"px;"+g+";filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+a.src+"', sizingMethod='scale');\">"}}}function getBigImage(a){if(a=="")return"";var b=getFileExt(a);return b=="GIF"||b=="PNG"?a:b=="JPG"||b=="JPEG"?a.replace("-s.","-b."):a}function getSmallImage(a){if(a=="")return"";var b=getFileExt(a);return b=="GIF"||b=="PNG"?a:b=="JPG"||b=="JPEG"?a.replace("-b.","-s."):a}function createWebEditor(a,b,c,f,g,h){return(new WebPage).createWebEditor(a,b,c,f,g,h)}
function writeWebEditor(a,b,c,f,g,h){document.write(createWebEditor(a,b,c,f,g,h))}function writeModule(){document.write(createModule.apply(this,arguments))}
function createModule(){var a=new ImageFilesSelector(_WebPageInfo),b=$A(arguments),c=b[0],f=b[1],g=b[2],h=b[3],j=0;b.length>4&&(j=b[4]);var k="";b.length>5&&(k=b[5]);var l="";b.length>6&&(l=b[6]);var m="";b.length>7&&(m=b[7]);var n="";b.length>8&&(n=b[8]);if(f=="")return createImage("","",0,0,0,k,l,m);else if(a.CheckExt(f,a.WebPageInfo.ImageInfo.exts)!=0)return c==""&&f.indexOf("/")==-1?c=_WebPageInfo.UserPath+"gallery/":c!=""&&(c+="gallery/"),createImage(c,f,g,h,j,k,l,m);else if(a.CheckExt(f,a.WebPageInfo.DigitalMediaInfo.exts)!=
0)return c==""&&f.indexOf("/")==-1?c=_WebPageInfo.UserPath+"files/":c!=""&&(c+="files/"),createMdeia(c,f,g,h,k,l,m,n);else if(a.CheckExt(f,a.WebPageInfo.FlashInfo.exts)!=0)return c==""&&f.indexOf("/")==-1?c=_WebPageInfo.UserPath+"files/":c!=""&&(c+="files/"),createFlash(c,f,g,h,k,l,m,n);else if(a.CheckExt(f,a.WebPageInfo.ThreeDInfo.exts)!=0)return c==""&&f.indexOf("/")==-1?c=_WebPageInfo.UserPath+"files/":c!=""&&(c+="files/"),create3D(c,f)}
function writeImage(a,b,c,f,g,h,j,k){g||(g=0);h||(h="");j||(j="");k||(k="");document.write(createImage(a,b,c,f,g,h,j,k))}
function createImage(a,b,c,f,g,h,j,k){var l="";h||(h="");j||(j="");k||(k="");var m=getBigImage(b);h!=""&&(l+='<a href="'+h+'" target="'+j+'">');b==""?l+='<i class="defaultPic"></i>':(l+='<img width="0" height="0" src="'+a+b+'" \t       onload="AutoResizeImage('+c+","+f+',this)" '+k+" ",l+='onerror="loadImageError(this);" ',g==1&&(l+=" onmouseover=\"SmePreviewBigImage.mouseenter(event,'"+a+m+"',450,450)\" "),l+="/>");h!=""&&(l+="</a>");return l}
function loadImageError(a){a.onload=function(){};$(a.parentNode);a.outerHTML='<i class="defaultPic"></i>'}
var SmePreviewBigImage={initialize:!1,id:"previewimagediv",imageId:"previewBigImageUid",zoommaskdiv:"previewzoommaskid",zoomdiv:"previewzoomdivid",viewimg:"previewviewimageid",className:"previewImg",imageSrc:null,imageContainer:null,image:null,loadingimg:null,imageLoadEvent:null,isimage:!0,mouseEvent:null,zoomEvent:null,x:0,y:0,width:450,height:450,currentEffect:null,ps:null,scrollsize:null,documentbody:null,init:function(){this.documentbody=document.body;this.imageContainer=$(document.createElement("div"));
this.imageContainer.writeAttribute({id:this.id,"class":this.className});this.imageContainer.setStyle({display:"none",background:"#fff",padding:"1px",border:"#666666 solid 5px",position:"absolute",zIndex:1E4});this.documentbody.insertBefore(this.imageContainer,this.documentbody.firstChild);this.mouseEvent=this.mouseleave.bindAsEventListener(this);Event.observe(this.imageContainer,"mouseout",this.mouseEvent);this.clickEvent=this.documentClick.bindAsEventListener(this);Event.observe(document,"click",
this.clickEvent);this.imageLoadEvent=this.imageload.bindAsEventListener(this);this.loadingimg=$(document.createElement("img"));this.loadingimg.writeAttribute({id:"previewloadingimg","class":"img",src:IMPORTJS.path+"loading.gif"});this.initialize=!0},zoom:function(){},documentClick:function(a){a=a.srcElement||a.target;!$(a).descendantOf(this.id)&&a!=this.imageSrc&&$(this.id).hide()},imageload:function(a){this.imageContainer.hide();a=a.srcElement||a.target;a=getRadio(a.width,a.height,this.width,this.height);
Event.stopObserving(this.image,"load",this.imageLoadEvent);this.image.writeAttribute({radio:a.radio});this.image.setStyle({display:"block",width:a[0]+"px",height:a[1]+"px"});this.imageContainer.update("");this.imageContainer.appendChild(this.image);var b=2*this.imageContainer.getStyle("border-left-width").replace("px","");if(this.x+a[0]+b>this.ps[0])this.x=this.x-a[0]-b;if(this.x<0)this.x=0;if(this.y+a[1]+b>this.ps[1])this.y=this.y-a[1]-b;if(this.y<0)this.y=0;this.imageContainer.setStyle({top:this.y+
"px",left:this.x+"px"});this.currentEffect=Effect.Appear(this.imageContainer)},mouseenter:function(a,b,c,f){var g=a.fromElement||a.relatedTarget,a=$(a.srcElement||a.target);if(g&&a!=this.imageSrc){this.initialize||this.init();if(a.src&&(b==null||b==""))b=getBigImage(a.src);this.imageContainer.update(this.loadingimg.outerHTML);if(objInvalid.checkExt(b,_WebPageInfo.ImageInfo.exts)==0&&objInvalid.checkExt(b,_WebPageInfo.FlashInfo.exts)==0&&objInvalid.checkExt(b,_WebPageInfo.ThreeDInfo.exts)==0)return!1;
if(c)this.width=c;if(f)this.height=f;this.imageSrc=a;if(this.imageSrc.tagName.toUpperCase()!="IMG")this.isimage=!1;this.ps=document.viewport.getPage();this.scrollsize=document.viewport.getScrollOffsets();c=Element.viewportOffset(this.imageSrc);this.isimage?(this.x=c.left+this.imageSrc.width/2+this.scrollsize.left,this.y=c.top+this.imageSrc.height/2+this.scrollsize.top):(this.x=c.left+this.imageSrc.getWidth()/2+this.scrollsize.left,this.y=c.top+this.imageSrc.getHeight()/2+this.scrollsize.top);this.imageContainer.setStyle({top:this.y+
"px",left:this.x+"px"});this.imageContainer.show();if(this.image)Event.stopObserving(this.image,"load",this.imageLoadEvent),this.image=null;this.image=$(document.createElement("img"));this.image.writeAttribute({id:this.imageId,"class":"img"});Event.observe(this.image,"load",this.imageLoadEvent);this.image.src=b;Event.observe(this.imageSrc,"mouseout",this.mouseEvent)}},mouseleave:function(a){if((a=a.toElement||a.relatedTarget)&&a!=this.imageSrc&&a.id!=this.id&&a.id!=this.imageId&&a.id!=this.zoommaskdiv&&
a.id!=this.zoomdiv&&a.id!=this.viewimg&&a.id!="previewloadingimg")this.currentEffect&&this.currentEffect.cancel(),Event.stopObserving(this.imageSrc,"mouseout",this.mouseEvent),Event.stopObserving(this.image,"load",this.imageLoadEvent),this.imageSrc=this.image=null,this.imageContainer.hide()}};function writeFlash(a,b,c,f,g,h,j,k){document.write(createFlash(a,b,c,f,g,h,j,k))}
function createFlash(a,b,c,f,g,h,j,k){return k!=""?createImage(k,"icon_swf.png",c,f,0,g,h,j+' class="fswficon" '):(g=getFileSize(b),c=getRadio(g[0],g[1],c,f),a=new SWFObject(a+b,"smeshopswfflash",c[0],c[1],"9","#FF6600"),a.addVariable("auto","0"),html=a.getSWFHTML())}function writeMedia(a,b,c,f,g,h,j,k){document.write(createMedia(a,b,c,f,g,h,j,k))}
function createMedia(a,b,c,f,g,h,j,k){k||(k="");return k!=""?createImage(k,"icon_video.png",c,f,0,g,h,j):(g="",(h=getFileSize(b))?(c=getRadio(h[0],h[1],c,f),c[1]+=50):c=c&&f?[c,f]:[130,100],g+="<embed src="+(a+b)+" width="+c[0]+" height="+c[1]+' autostart=false controls="controlpanel/playbutton" loop=false></embed>',g)}function writeLink(a,b,c,f){document.write(createLink(a,b,c,f))}
function createLink(a,b,c){var f="";return a!=""&&b!=""?(f+='<a href="'+b+'" target="'+c+'">'+a+"</a>",f):a==""&&b!=""?(f+='<a href="'+b+'" target="'+c+'">'+b+"</a>",f):""}function getFileSize(a){var b=a.split("\\.")[0].split("_");return b.length!=3?[0,0]:(a=parseInt(isNaN(parseInt(b[1]))?0:b[1]),b=parseInt(isNaN(parseInt(b[2]))?0:b[2]),[a,b])}function getRandom(a){return Math.round(Math.random()*Math.pow(10,a))}
function getEffectRand(){var a=Math.round(Math.random()*30);return a>23?this.getEffectRand():a}var Ads=Class.create();
Ads.prototype={initialize:function(){if(arguments!=null){if(arguments[0]!=null)this.id=arguments[0],this.parent=$(arguments[0]),this.numberTab="number"+this.id,this.contentTab="content"+this.id;if(arguments[1]!=null)this.height=arguments[1];if(arguments[2]!=null)this.path=arguments[2];if(arguments[3]!=null)this.adsData=arguments[3];if(arguments[4]!=null)this.objectAds=arguments[4];if(arguments[5]!=null)this.isAutoScroll=arguments[5]}this.adsWidth=200;this.currentId="";this.currentIndex=0;this.firstRand=
"";this.totalAds=this.adsData.length;this.adsHander=this;this.numbers=[];this.interval=null;this._createAdsModule();this.startTime=(new Date).getTime();this.switchAds($("l"+this.currentId));if(this.isAutoScroll)this.interval=window.setInterval(this.objectAds+".autoScroll()",4E3)},_createAdsModule:function(){this.parent.innerHTML='<div class="tpbnbox">\t\t\t<div class="tpbntabs">\t\t\t\t<div class="tpbntabsbg">\t\t\t\t\t<span class="tabCell" id="'+this.numberTab+'">\t\t\t\t\t</span>\t\t\t\t</div>\t\t\t</div>\t\t\t<ol class="tpbnpans" id="'+
this.contentTab+'">\t\t\t</ol>\t\t</div>';var a=$($(this.numberTab).parentNode.parentNode.parentNode);a.setStyle({height:this.height+"px"});this.adsWidth=a.getWidth();this._createAds()},_createAds:function(){for(var a=this.objectAds,b=this.adsHander,c=0;c<this.adsData.length;c++){var f=this.getRandom(5),g=this.adsData[c],h=document.createElement("a"),h=$(h);h.setAttribute("id","l"+f);h.setAttribute("href","javascript:void(0);");h.setAttribute("title",g.name.encodeToHtml());h.index=c;h.rand=f;var j=
document.createTextNode(c+1);h.appendChild(j);if(c==0)this.currentId=f,this.currentIndex=c,h.addClassName("current");h.onclick=function(){b.currentId!=this.rand&&b.switchAds(this);if(b.isAutoScroll)window.clearInterval(eval(a+".interval")),b.interval=window.setInterval(a+".autoScroll()",4E3);return!1};this.numbers[c]=h;$(this.numberTab).appendChild(h);h=document.createElement("li");h=$(h);h.setAttribute("id","li"+f);h.addClassName("pan");h.style.display="";h.style.visibility="hidden";j=f="";if(f!=
null&&f!=void 0&&f!="")f=g.url,j="_blank";g.image==""?(h.isImage=!1,h.addClassName("hover"),h.innerHTML=f==""?'<div class="contentBox"><div class="contentBoxBg"><h4>'+g.name+"</h4>"+g.text.encodeToHtml()+"</div></div>":'<div class="contentBox"><div class="contentBoxBg"><h4><a href="'+f+'" target="_blank">'+g.name+'</a></h4><a href="'+f+'" target="_blank">'+g.text.encodeToHtml()+"</a></div></div>"):(h.isImage=!0,h.removeClassName("hover"),h.onmouseover=function(){$(this).addClassName("hover")},h.onmouseout=
function(){$(this).removeClassName("hover")},h.innerHTML="<div>"+createModule(this.path,g.image,this.adsWidth,this.height,0,f,j,' alt="" ')+"</div>",h.innerHTML+=f==""?'<div class="contentBox"><div class="contentBoxBg"><h4>'+g.name+"</h4>"+g.text.encodeToHtml()+"</div></div>":'<div class="contentBox"><div class="contentBoxBg"><h4><a href="'+f+'" target="_blank" hidefocus="true">'+g.name+'</a></h4><a href="'+f+'" target="_blank" hidefocus="true">'+g.text.encodeToHtml()+"</a></div></div>");if(c==0)this.firstRand=
f=this.getRandom(5),g=document.createElement("li"),g=$(g),g.setAttribute("id","li"+f),g.addClassName("pan"),g.style.display="",g.style.visibility="visible",h.isImage?(g.removeClassName("hover"),g.onmouseover=function(){$(this).addClassName("hover")},g.onmouseout=function(){$(this).removeClassName("hover")}):g.addClassName("hover"),g.innerHTML=h.innerHTML,$(this.contentTab).appendChild(g);$(this.contentTab).appendChild(h)}this.adsData.length<=1&&$($(this.numberTab).parentNode.parentNode).hide()},switchAds:function(a){if(this.isIE5Up()){var b=
$("li"+a.rand),c=$("li"+this.firstRand);c.style.filter="blendTrans(duration=1.5) revealTrans(duration=1.0,transition="+this.getEffectRand()+")";c.filters(0).apply();c.filters(1).apply();b.isImage?(c.removeClassName("hover"),c.onmouseover=function(){$(this).addClassName("hover")},c.onmouseout=function(){$(this).removeClassName("hover")}):(c.addClassName("hover"),c.onmouseover=function(){},c.onmouseout=function(){});c.innerHTML=b.innerHTML;c.filters(0).play();c.filters(1).play()}else this.currentId!=
a.rand&&this.fadeOut(this.currentId,99.999),this.fadeIn(a.rand,0);$("l"+a.rand).addClassName("current");this.currentId!=a.rand&&$("l"+this.currentId).removeClassName("current");this.currentId=a.rand;this.currentIndex=a.index;this.startTime=(new Date).getTime()},autoScroll:function(){this.currentIndex+1<this.totalAds?this.switchAds(this.numbers[this.currentIndex+1]):this.switchAds(this.numbers[0])},getRandom:function(a){return Math.round(Math.random()*Math.pow(10,a))},getEffectRand:function(){var a=
Math.round(Math.random()*30);return a>23?this.getEffectRand():a},isIE5Up:function(){var a=navigator.userAgent,b=a.indexOf("MSIE");return b<0?!1:parseInt(a.substring(b+5,a.indexOf(".",b)))>=5},setOpacity:function(a,b){if(a!=null)b=b==100?99.999:b,a.style.filter="alpha(opacity:"+b+")",a.style.KHTMLOpacity=b/100,a.style.MozOpacity=b/100,a.style.opacity=b/100},fadeOut:function(a,b){var c=$("li"+a);if(c!=null)b>-1?(this.setOpacity(c,b),b-=10,window.setTimeout(this.objectAds+".fadeOut('"+a+"',"+b+")",100)):
(c.style.visibility="hidden",c.style.zIndex=1)},fadeIn:function(a,b){var c=$("li"+a);if(c!=null&&b<=99.999)c.style.visibility="visible",c.style.zIndex=9999,this.setOpacity(c,b),b+=10,window.setTimeout(this.objectAds+".fadeIn('"+a+"',"+b+")",100)}};
Object.extend(String.prototype,{encodeToHtml:function(){return this.gsub(/\n/,"<br/>")},escapeQuot:function(a){return a?this.gsub(/"/,"&quot;"):this.escapeHTML().gsub(/"/,"&quot;")},unescapeQuot:function(a){return a?this.gsub(/"/,"&quot;"):this.unescapeHTML().gsub(/"/,"&quot;")},escapeSpecialChar:function(){var a=this.replace(/'/g,"&#39;");return a=a.replace(/"/g,"&#34")}});
function showSelectBoxes(){var a=document.getElementsByTagName("select");for(i=0;i!=a.length;i++)a[i].style.visibility="visible"}function hideSelectBoxes(){var a=document.getElementsByTagName("select");for(i=0;i!=a.length;i++)a[i].style.visibility="hidden"}function showFlash(){var a=document.getElementsByTagName("object");for(i=0;i<a.length;i++)a[i].style.visibility="visible";a=document.getElementsByTagName("embed");for(i=0;i<a.length;i++)a[i].style.visibility="visible"}
function hideFlash(){var a=document.getElementsByTagName("object");for(i=0;i<a.length;i++)a[i].style.visibility="hidden";a=document.getElementsByTagName("embed");for(i=0;i<a.length;i++)a[i].style.visibility="hidden"}var TEMPLATE_STATUS_BAR_TEXT="Welecome to our website !",TEMPLATE_PLACE=1;
function windowStatusScrollIn(){window.status=TEMPLATE_STATUS_BAR_TEXT.substring(0,TEMPLATE_PLACE);TEMPLATE_PLACE>=TEMPLATE_STATUS_BAR_TEXT.length?(TEMPLATE_PLACE=1,window.setTimeout("windowStatusScroll()",200)):(TEMPLATE_PLACE++,window.setTimeout("windowStatusScrollIn()",100))}
function windowStatusScroll(){window.status=TEMPLATE_STATUS_BAR_TEXT.substring(TEMPLATE_PLACE,TEMPLATE_STATUS_BAR_TEXT.length);TEMPLATE_PLACE>=TEMPLATE_STATUS_BAR_TEXT.length?(TEMPLATE_PLACE=1,window.setTimeout("windowStatusScrollIn()",200)):(TEMPLATE_PLACE++,window.setTimeout("windowStatusScroll()",100))}var switchTimer=null;
function switchTab(a,b,c,f){if($(b+c)){switchTimer&&clearTimeout(switchTimer);for(var g=!0,h=0;h<a;h++)if(!$(b+h)||!$(b+"btn"+h)){g=!1;break}if(g)for(h=0;h<a;h++)f=$(b+h),g=$(b+"btn"+h),f&&g&&(c==h?(f.removeClassName("eleHid"),g.addClassName("select")):(f.addClassName("eleHid"),g.removeClassName("select")));else{if(f==null||f=="undefined")h=$(b+"btn0"),f=$(b+"btn1"),h&&f?(pos0=h.viewportOffset(),pos1=f.viewportOffset(),f=pos1.top-pos0.top<4?"TC":"TL"):f="TL";switchTimer=setTimeout(switchTab.bind(this,
a,b,c,f),2500)}}}function switchBlind(a,b){$(a).up("div.subFunctionLi").toggleClassName(b)}function selectCategoryTree(a,b){$$("#"+a+" div.treeLink").each(function(a){$(a).removeClassName("current")});var c=$(b).up(0).down("ul.treeSub");$(b).hasClassName("open")?(c&&c.toggleClassName("openSub"),$(b).removeClassName("open"),$(b).addClassName("close")):(c&&c.toggleClassName("openSub"),$(b).removeClassName("close"),$(b).addClassName("open"));$(b).addClassName("current")}
function selectMoveCategoryTree(a,b){$$("#"+a+" div.treeLink").each(function(a){$(a).removeClassName("current")});$(b).addClassName("current")}
Browser={agent:function(){return window.navigator.userAgent},agentContains:function(a){return Browser.agent().indexOf(a)!=-1},ie:function(){return Browser.agentContains("MSIE")},gecko:function(){return Browser.agentContains("Gecko")},firefox:function(){throw"Use Browser.gecko() instead";},version:function(){var a=Browser.agent();return Browser.ie()?parseFloat(a.split("MSIE")[1]):parseFloat(a.split("/")[1])},ie5_up:function(){return Browser.ie()&&Browser.version()>=5},ie5_5up:function(){return Browser.ie()&&
Browser.version()>=5.5}};
SmePosition={button:null,objDiv:null,classNamePrefix:"rBox3Position",className:"BC",buttonPosition:null,divPosition:null,scrollOffset:null,pageSize:null,offset:{x:0,y:0},tipNoFix:function(a,b,c,f,g,h,j){this.tip(a,b,c,f,g,h,j,!0)},tip:function(a,b,c,f,g,h,j,k){(!a||!b)&&alert("SmePosition.tip() parameters error , btn is not null, div is not null");j=j==null||j==void 0?"noteMsg":j;this.button=$(a);this.objDiv=$(b);if(h==null||h=="undefined")h=["productTagTipBox","tipPopBox1"];alert(a);for(a=0;a<h.length;a++)this.objDiv.addClassName(h[a]);
this.classNamePrefix=h[h.length-1];this.className=g?g:"TL";f=f==null||f=="undefined"?!0:!1;this.mouseEvent=this.mouseleave.bindAsEventListener(this);f&&(Event.observe(this.button,"mouseout",this.mouseEvent),Event.observe(this.objDiv,"mouseout",this.mouseEvent));this.objDiv.removeClassName("eleHid");this.objDiv.show();var l=this.objDiv.down("div.tipPopContentUpdate");l&&l.update(c);if(l=this.objDiv.down("div.msgContent"))$w("noteMsg loadingMsg okMsg errorMsg warningMsg").each(function(a){l.removeClassName(a)}),
l.addClassName(j);this.setPosition(this.button,this.objDiv,this.className,this.classNamePrefix,k)},mouseleave:function(a){a=a.toElement||a.relatedTarget;a!=this.objDiv&&a!=this.button&&!this.inContainer(this.objDiv,a)&&this.objDiv.addClassName("eleHid")},inContainer:function(a,b){var c=$(a).childElements();if($(a)==b)return!0;for(var f=0;f<c.length;f++){if(b==c[f])return!0;if(this.inContainer(c[f],b))return!0}return!1},setPosition:function(a,b,c,f,g){g=g==null||g=="undefined"||!g?!1:!0;this.button=
$(a);this.objDiv=$(b);if(f)this.classNamePrefix=f;if(c)this.className=c;this.scrollOffset=document.viewport.getScrollOffsets();this.pageSize=document.viewport.getPage();this.buttonPosition=this.getPosition(this.button);this.divPosition=this.getPosition(this.objDiv);var h=null,b=this.className.toArray(),a=b[0],b=b[1],f=c=0,h=this.getLeft(b,g),f=h.left,b=h.css,h=this.getTop(a,g),c=h.top,a=h.css,h=[f,c];h.left=f;h.top=c;h.className=this.classNamePrefix+a+b;$w("TL TC TR BL BC BR ML MR").each(function(a){this.objDiv.removeClassName(this.classNamePrefix+
a)}.bindAsEventListener(this));this.objDiv.removeClassName("eleHid");this.objDiv.show();this.objDiv.addClassName(h.className);this.objDiv.setStyle({left:h.left+ +this.scrollOffset.left+"px",top:h.top+this.scrollOffset.top+"px"})},getLeft:function(a,b){var c="R",f=-1,g=-1,h=-1,h=this.buttonPosition.left-this.divPosition.width;h+=b?this.buttonPosition.width:this.buttonPosition.width/2;f=h;if(h<0||a&&(a=="C"||a=="L"))f=g=this.buttonPosition.left-this.divPosition.width/2+this.buttonPosition.width/2,g<
0||a&&a=="L"?(h=this.buttonPosition.left,b||(h+=this.buttonPosition.width/2),f=h,c="L",h+this.divPosition.width>this.scrollOffset.left+this.pageSize[0]&&(f=g,c="C")):(c="C",g+this.divPosition.width>this.scrollOffset.left+this.pageSize[0]&&(f=h,c="R"));g=[f,c];g.left=f;g.css=c;return g},getTop:function(a){var b="B",c=-1,f=-1,g=-1,c=f=this.buttonPosition.top-this.divPosition.height;if(f<0||a&&(a=="M"||a=="T"))c=g=this.buttonPosition.top-this.divPosition.height/2+this.buttonPosition.height/2,g<0||a&&
a=="T"?(c=f=this.buttonPosition.top+this.buttonPosition.height,b="T",f+this.divPosition.height>this.scrollOffset.top+this.pageSize[1]&&(c=g,b="M")):(b="M",g+this.divPosition.height>this.scrollOffset.top+this.pageSize[1]&&(c=f,b="B"));a=[c,b];a.top=c;a.css=b;return a},getT:function(){return this.buttonPosition.top+this.buttonPosition.height},getM:function(){return this.buttonPosition.top-this.divPosition.height/2+this.buttonPosition.height/2},getB:function(){return this.buttonPosition.top-this.divPosition.height},
getL:function(){return this.buttonPosition.left+this.buttonPosition.width},getC:function(){return this.buttonPosition.left-this.divPosition.width/2+this.buttonPosition.width/2},getR:function(){return this.buttonPosition.left-this.divPosition.width},getFixL:function(){return this.buttonPosition.left},getFixR:function(){return this.buttonPosition.left-this.divPosition.width+this.buttonPosition.width},getPosition:function(a){var a=$(a),b=a.getStyle("display")=="none"||a.hasClassName("eleHid");b&&(a.removeClassName("eleHid"),
a.show());var c=a.getDimensions(),f=a.viewportOffset(),g=[c.width,c.height,f.left,f.top];g.width=c.width;g.height=c.height;g.left=f.left;g.top=f.top;b&&(a.addClassName("eleHid"),a.hide());return g},closeTip:function(){this.objDiv?(this.objDiv.addClassName("eleHid"),this.objDiv.hide()):$("tip")?($("tip").addClassName("eleHid"),$("tip").hide()):$("adminTipBox")&&($("adminTipBox").addClassName("eleHid"),$("adminTipBox").hide())}};
function addParams(a,b){if(a==null||a=="undefined"||a=="")alert("url is undefined or null or ''.");else{a=a.gsub("&amp;","&");if(b==null||b=="undefined")b={};var c={},f=c=a,g=a.indexOf("?");g==-1?c=a+"?":f=a.substr(0,g);c=$H(c.toQueryParams());g=$H(b);g.update({rnd:Math.random()});c.update(g);return f+"?"+c.toQueryString()}}
function addParamsJson(a,b,c){if(a==null||a=="undefined"||a=="")alert("url is undefined or null or ''.");else{a=a.gsub("&amp;","&");if(!(b==null||b=="undefined"))for(var f=0;f<b.length;f++)a.indexOf("?"+b[f].name+"=")==-1&&a.indexOf("&"+b[f].name+"=")==-1&&(a+=(a.indexOf("?")!=-1?"&":"?")+b[f].name+"="+escape(b[f].value));c&&a.indexOf("?rnd=")==-1&&a.indexOf("&rnd=")==-1&&(a+=a.indexOf("?")!=-1?"&rnd="+Math.random():"?rnd="+Math.random());return a}}
function encode(a){return encodeURIComponent(a)}function decode(a){return decodeURIComponent(a.replace(/\+/g," "))}
var parseCssJson={effects:["dropshadow","shadow","glow"],oldcss:"",oldjson:{},css:"",json:{},setCss:function(a){parseCssJson.css=a.gsub(/@charset "utf\-8";/ig,"");parseCssJson.oldcss=parseCssJson.css;parseCssJson.json=parseCssJson.toJSON();parseCssJson.oldjson=parseCssJson.json},getStyle:function(a){for(var b=a.split("["),c="parseCssJson.json",f=0;f<b.length;f++)if(b[f]!=""&&(c+="["+b[f],eval(c)==void 0))return"";return(a=eval("parseCssJson.json"+a))?a:""},setStyle:function(a,b){for(var a=a.substr(2,
a.length-4),c=a.split('"]["'),f="parseCssJson.json",g=0;g<c.length;g++)eval(f)[c[g]]==void 0&&g<c.length-1&&(eval(f)[c[g]]={}),g==c.length-1&&(eval(f)[c[g]]=b),f+='["'+c[g]+'"]';parseCssJson.css=parseCssJson.toCSS()},toCSS:function(a,b,c){if(!a)a=parseCssJson.json;var f="",g;for(g in a){var h="";f+=g+" {\n";for(var j in a[g])if(j.indexOf("filter")!=-1){h+="\t"+j+":";for(var k in a[g][j])if((","+c+",").indexOf(',["'+g+'"]["'+j+'"]["'+k+'"],')!=-1){var l=0;h+=k+"(";for(var m in a[g][j][k])l>0&&(h+=
", "),h+=m+"="+a[g][j][k][m],l++;h+=")"}h+=";\n"}else h+="\t"+j+":"+a[g][j]+";\n";if(g==b||'["'+g+'"]'==b)return h;f+=h+"}\n"}return f},toJSON:function(a){if(!a)a=parseCssJson.css;a=parseCssJson.parseCssToJSON(0,a);return eval("("+a+")")},parseCssToJSON:function(a,b){if(!b)b=parseCssJson.css;var c="",a=!a||a==0?0:a,f=b.indexOf("{",a);if(f==-1)return"}";a==0&&(c+="{");a>0&&(c+=",");tag=b.substr(a,f-a);c+=parseCssJson.clearCssTag(tag).inspect(!0)+":{";var g=b.indexOf("}",f),h="",h=g!=-1?b.substring(f+
1,g):b.substr(f+1);c+=parseCssJson.parseAttribute(h)+"}";c+=parseCssJson.parseCssToJSON(g+1,b);return c},parseAttribute:function(a){if(!a)a=parseCssJson.css;for(var b="",a=a.split(";"),c=0;c<a.length;c++)if(a[c].strip()!="")if(c>0&&(b+=","),a[c].indexOf("(")!=-1){var f=a[c].split(":");b+=parseCssJson.clearCssTag(f[0]).inspect(!0)+":{";f=f[1].split("(");b+=parseCssJson.clearCssTag(f[0]).inspect(!0)+":{";for(var f=f[1].split(","),g=0;g<f.length;g++){var h=f[g].split("=");g>0&&(b+=",");g==f.length-1&&
(h[1]=h[1].gsub(/\)/,""));b+=parseCssJson.clearCssTag(h[0]).inspect(!0)+":"+parseCssJson.clearCssValue(h[1]).inspect(!0)}b+="}}"}else f=a[c].split(":"),b+=parseCssJson.clearCssTag(f[0]).inspect(!0)+":"+parseCssJson.clearCssValue(f[1]).inspect(!0);return b},clearCssValue:function(a){return a=(""+a).strip()},clearCssTag:function(a){return a.gsub(/\r/,"").gsub(/\n/,"").gsub('"',"").strip()},getEffectName:function(a){for(var b=0;b<parseCssJson.effects.length;b++){var c=parseCssJson.effects[b];if(eval("parseCssJson.json"+
a+'["'+c+'"]'))return c}return""},getFontStyle:function(a,b){a=a==""?"normal":a;b=b==""?"normal":b;return a!="normal"&&b=="normal"?"bold&italic":a!="normal"?a:b!="normal"?b:"normal"},parseFontStyle:function(a){var b=[],a=a.split("&");if(a.length>1)return b=[a[0],a[1]],b.style=a[1],b.weight=a[0],b;else if(a[0]=="normal")return b=["normal","normal"],b.style="normal",b.weight="normal",b;else if(a[0]=="bold")return b=["normal","bold"],b.style="normal",b.weight="bold",b;else if(a[0]=="italic")return b=
["italic","normal"],b.style="italic",b.weight="normal",b}};
