document.write("<div id=meizzCalendarLayer style='position: absolute; z-index: 9999; width: 194px; height: 193px; display: none'>");document.write("<iframe name=meizzCalendarIframe scrolling=no frameborder=0 width=100% height=100%></iframe></div>");
function writeIframe(){var a="<html><head><meta http-equiv='Content-Type' content='text/html; charset=utf-8'><style>*{font-size: 12px; font-family: arial}.bg{  color: "+WebCalendar.lightColor+"; cursor: default; background-color: "+WebCalendar.darkColor+";}table#tableMain{ width: 190; height: 180;}table#tableWeek td{ color: "+WebCalendar.lightColor+";}table#tableDay  td{ font-weight: bold;}td#meizzYearHead, td#meizzYearMonth{color: "+WebCalendar.wordColor+"}.out { text-align: center; border-top: 1px solid "+
WebCalendar.DarkBorder+"; border-left: 1px solid "+WebCalendar.DarkBorder+";border-right: 1px solid "+WebCalendar.lightColor+"; border-bottom: 1px solid "+WebCalendar.lightColor+";}.over{ text-align: center; border-top: 1px solid #FFFFFF; border-left: 1px solid #FFFFFF;border-bottom: 1px solid "+WebCalendar.DarkBorder+"; border-right: 1px solid "+WebCalendar.DarkBorder+"}input{ border: 1px solid "+WebCalendar.darkColor+"; padding-top: 1px; height: 18; cursor: hand;       color:"+WebCalendar.wordColor+
"; background-color: "+WebCalendar.btnBgColor+"}</style></head><body onselectstart='return false' style='margin: 0px' oncontextmenu='return false'><form name=meizz>";WebCalendar.drag&&(a+="<script language=javascript>var drag=false, cx=0, cy=0, o = parent.WebCalendar.calendar; function document.onmousemove(){if(parent.WebCalendar.drag && drag){if(o.style.left=='')o.style.left=0; if(o.style.top=='')o.style.top=0;o.style.left = parseInt(o.style.left) + window.event.clientX-cx;o.style.top  = parseInt(o.style.top)  + window.event.clientY-cy;}}function document.onkeydown(){ switch(window.event.keyCode){  case 27 : parent.hiddenCalendar(); break;case 37 : parent.prevM(); break; case 38 : parent.prevY(); break; case 39 : parent.nextM(); break; case 40 : parent.nextY(); break;case 84 : document.forms[0].today.click(); break;} window.event.keyCode = 0; window.event.returnValue= false;}function dragStart(){cx=window.event.clientX; cy=window.event.clientY; drag=true;}<\/script>");
a+="<select name=tmpYearSelect  onblur='parent.hiddenSelect(this)' style='z-index:1;position:absolute;top:3;left:18;display:none' onchange='parent.WebCalendar.thisYear =this.value; parent.hiddenSelect(this); parent.writeCalendar();'></select><select name=tmpMonthSelect onblur='parent.hiddenSelect(this)' style='z-index:1; position:absolute;top:3;left:74;display:none' onchange='parent.WebCalendar.thisMonth=this.value; parent.hiddenSelect(this); parent.writeCalendar();'></select><table id=tableMain class=bg border=0 cellspacing=2 cellpadding=0><tr><td width=190 height=19 bgcolor='"+
WebCalendar.lightColor+"'>    <table width=190 id=tableHead border=0 cellspacing=1 cellpadding=0><tr align=center>    <td width=27 height=19 class=bg title='\u4e0a\u4e00\u6708' style='cursor: hand' onclick='parent.prevM()'><b>&lt;</b></td>    <td width=75 id=meizzYearHead  title='\u9ede\u64ca\u9019\u88cf\u9078\u64c7\u5e74\u4efd' onclick='parent.funYearSelect(parseInt(this.innerText, 10))'        onmouseover='this.bgColor=parent.WebCalendar.darkColor; this.style.color=parent.WebCalendar.lightColor'        onmouseout='this.bgColor=parent.WebCalendar.lightColor; this.style.color=parent.WebCalendar.wordColor'></td>    <td width=63 id=meizzYearMonth title='\u9ede\u64ca\u9019\u88cf\u9078\u64c7\u6708\u4efd' onclick='parent.funMonthSelect(parseInt(this.innerText, 10))'        onmouseover='this.bgColor=parent.WebCalendar.darkColor; this.style.color=parent.WebCalendar.lightColor'        onmouseout='this.bgColor=parent.WebCalendar.lightColor; this.style.color=parent.WebCalendar.wordColor'></td>    <td width=27 class=bg title='\u4e0b\u4e00\u6708' onclick='parent.nextM()' style='cursor: hand'><b>&gt;</b></td></tr></table></td></tr><tr><td height=20><table id=tableWeek border=1 width=190 cellpadding=0 cellspacing=0 ";
WebCalendar.drag&&(a+="onmousedown='dragStart()' onmouseup='drag=false' onmouseout='drag=false'");a+=" borderColorLight='"+WebCalendar.darkColor+"' borderColorDark='"+WebCalendar.lightColor+"'>    <tr align=center><td height=20>\u4e00</td><td>\u4e8c</td><td>\u4e09</td><td>\u56db</td><td>\u4e94</td><td>\u516d</td><td>\u65e5</td></tr></table></td></tr><tr><td valign=top width=190 bgcolor='"+WebCalendar.lightColor+"'>    <table id=tableDay height=120 width=190 border=0 cellspacing=1 cellpadding=0>";
for(var c=0;c<5;c++){a+="<tr>";for(var b=0;b<7;b++)a+="<td class=out id='meizzDay"+(c*7+b)+"'></td>";a+="</tr>"}a+="<tr>";for(c=35;c<39;c++)a+="<td class=out id='meizzDay"+c+"'></td>";a+="<td colspan=3 class=out title='"+WebCalendar.regInfo+"'><input style=' background-color: "+WebCalendar.btnBgColor+";cursor: hand; padding-top: 4px; width: 100%; height: 100%; border: 0' onfocus='this.blur()' type=button value='&nbsp; &nbsp;\u95dc\u9589' onclick='parent.hiddenCalendar()'></td></tr></table></td></tr><tr><td height=20 width=190 bgcolor='"+
WebCalendar.lightColor+"'>    <table border=0 cellpadding=1 cellspacing=0 width=190>    <tr><td><input name=prevYear title='\u4e0a\u4e00\u5e74\u4efd' onclick='parent.prevY()' type=button value='&lt;&lt;'    onfocus='this.blur()' style='meizz:expression(this.disabled=parent.WebCalendar.thisYear==1000)'><input    onfocus='this.blur()' name=prevMonth title='\u4e0a\u4e00\u6708' onclick='parent.prevM()' type=button value='&lt;&nbsp;'>    </td><td align=center><input name=today type=button value='\u4eca\u5929' onfocus='this.blur()' style='width: 50' title='\u4eca\u5929'    onclick=\"parent.returnDate(new Date().getDate() +'/'+ (new Date().getMonth() +1) +'/'+ new Date().getFullYear())\">    </td><td align=right><input title='\u4e0b\u4e00\u6708' name=nextMonth onclick='parent.nextM()' type=button value='&nbsp;&gt;'    onfocus='this.blur()'><input name=nextYear title='\u4e0b\u4e00\u5e74\u4efd' onclick='parent.nextY()' type=button value='&gt;&gt;'    onfocus='this.blur()' style='meizz:expression(this.disabled=parent.WebCalendar.thisYear==9999)'></td></tr></table></td></tr><table></form></body></html>";
with(WebCalendar.iframe){document.writeln(a);document.close();for(a=0;a<39;a++)WebCalendar.dayObj[a]=eval("meizzDay"+a),WebCalendar.dayObj[a].onmouseover=dayMouseOver,WebCalendar.dayObj[a].onmouseout=dayMouseOut,WebCalendar.dayObj[a].onclick=returnDate}}
function WebCalendar(){this.regInfo="WEB Calendar ver 3.0Close shortcut key[Esc]";this.daysMonth=[31,28,31,30,31,30,31,31,30,31,30,31];this.day=Array(39);this.dayObj=Array(39);this.inputDate=this.eventSrc=this.objExport=this.dateStyle=null;this.thisYear=(new Date).getFullYear();this.thisMonth=(new Date).getMonth()+1;this.thisDay=(new Date).getDate();this.today=this.thisDay+"/"+this.thisMonth+"/"+this.thisYear;this.iframe=window.frames("meizzCalendarIframe");this.calendar=getObjectById("meizzCalendarLayer");
this.dateReg="";this.yearFall=50;this.format="yyyy-mm-dd";this.timeShow=!1;this.drag=!0;this.darkColor="#0000D0";this.lightColor="#FFFFFF";this.btnBgColor="#E6E6FA";this.wordColor="#000080";this.wordDark="#DCDCDC";this.dayBgColor="#F5F5FA";this.todayColor="#FF0000";this.DarkBorder="#D4D0C8"}WebCalendar=new WebCalendar;
function calendar(){var a=window.event.srcElement;writeIframe();var c=WebCalendar.calendar.style;WebCalendar.eventSrc=a;WebCalendar.objExport=arguments.length==0?a:eval(arguments[0]);WebCalendar.iframe.tableWeek.style.cursor=WebCalendar.drag?"move":"default";for(var b=a.offsetTop,d=a.clientHeight,e=a.offsetLeft,i=a.type;a=a.offsetParent;)b+=a.offsetTop,e+=a.offsetLeft;c.display="";WebCalendar.iframe.document.body.focus();var a=WebCalendar.calendar.clientWidth,f=WebCalendar.calendar.clientHeight,g=
document.body.clientWidth,h=document.body.scrollLeft,j=document.body.scrollTop;c.top=document.body.clientHeight+j-b-d>=f?i=="image"?b+d:b+d+6:b-j<f?i=="image"?b+d:b+d+6:b-f;c.left=g+h-e>=a?e:g>=a?g-a+h:h;WebCalendar.dateReg=WebCalendar.timeShow?/^(\d{1,4})(-|\/)(\d{1,2})\2(\d{1,2}) (\d{1,2}):(\d{1,2}):(\d{1,2})$/:/^(\d{1,4})(-|\/)(\d{1,2})\2(\d{1,2})$/;try{if(WebCalendar.objExport.value.trim()!="")if(WebCalendar.dateStyle=WebCalendar.objExport.value.trim().match(WebCalendar.dateReg),WebCalendar.dateStyle==
null)return WebCalendar.thisYear=(new Date).getFullYear(),WebCalendar.thisMonth=(new Date).getMonth()+1,WebCalendar.thisDay=(new Date).getDate(),alert("Date format is wrong!!"),writeCalendar(),!1;else WebCalendar.thisYear=parseInt(WebCalendar.dateStyle[1],10),WebCalendar.thisMonth=parseInt(WebCalendar.dateStyle[3],10),WebCalendar.thisDay=parseInt(WebCalendar.dateStyle[4],10),WebCalendar.inputDate=parseInt(WebCalendar.thisDay,10)+"/"+parseInt(WebCalendar.thisMonth,10)+"/"+parseInt(WebCalendar.thisYear,
10),writeCalendar();else writeCalendar()}catch(k){writeCalendar()}}function funMonthSelect(){for(var a=isNaN(parseInt(WebCalendar.thisMonth,10))?(new Date).getMonth()+1:parseInt(WebCalendar.thisMonth),c=WebCalendar.iframe.document.forms[0].tmpMonthSelect,b=1;b<13;b++)c.options.add(new Option(b+"\u6708",b));c.style.display="";c.value=a;c.focus();window.status=c.style.top}
function funYearSelect(){var a=WebCalendar.yearFall,c=WebCalendar.iframe.document.forms[0].tmpYearSelect,b=isNaN(parseInt(WebCalendar.thisYear,10))?(new Date).getFullYear():parseInt(WebCalendar.thisYear),b=b<=1E3?1E3:b>=9999?9999:b,d,e=b+a<=9999?b+a:9999;d=e==9999?e-a*2:b-a>=1E3?b-a:1E3;e=d==1E3?d+a*2:e;for(a=d;a<=e;a++)c.options.add(new Option(a+"\u5e74",a));c.style.display="";c.value=b;c.focus()}
function prevM(){WebCalendar.thisDay=1;if(WebCalendar.thisMonth==1)WebCalendar.thisYear--,WebCalendar.thisMonth=13;WebCalendar.thisMonth--;writeCalendar()}function nextM(){WebCalendar.thisDay=1;if(WebCalendar.thisMonth==12)WebCalendar.thisYear++,WebCalendar.thisMonth=0;WebCalendar.thisMonth++;writeCalendar()}function prevY(){WebCalendar.thisDay=1;WebCalendar.thisYear--;writeCalendar()}function nextY(){WebCalendar.thisDay=1;WebCalendar.thisYear++;writeCalendar()}
function hiddenSelect(a){for(var c=a.options.length;c>-1;c--)a.options.remove(c);a.style.display="none"}function getObjectById(a){return document.all?eval("document.all."+a):eval(a)}function hiddenCalendar(){getObjectById("meizzCalendarLayer").style.display="none"}function appendZero(a){return("00"+a).substr(("00"+a).length-2)}String.prototype.trim=function(){return this.replace(/(^\s*)|(\s*$)/g,"")};
function dayMouseOver(){this.className="over";this.style.backgroundColor=WebCalendar.darkColor;if(WebCalendar.day[this.id.substr(8)].split("/")[1]==WebCalendar.thisMonth)this.style.color=WebCalendar.lightColor}
function dayMouseOut(){this.className="out";var a=WebCalendar.day[this.id.substr(8)],c=a.split("/");this.style.removeAttribute("backgroundColor");if(c[1]==WebCalendar.thisMonth&&a!=WebCalendar.today){if(WebCalendar.dateStyle&&c[0]==parseInt(WebCalendar.dateStyle[4],10))this.style.color=WebCalendar.lightColor;this.style.color=WebCalendar.wordColor}}
function writeCalendar(){var a=WebCalendar.thisYear,c=WebCalendar.thisMonth,b=WebCalendar.thisDay;WebCalendar.daysMonth[1]=0==a%4&&(a%100!=0||a%400==0)?29:28;if(!(a<=9999&&a>=1E3&&parseInt(c,10)>0&&parseInt(c,10)<13&&parseInt(b,10)>0))alert("Sorry,you input invalid date!"),WebCalendar.thisYear=(new Date).getFullYear(),WebCalendar.thisMonth=(new Date).getMonth()+1,WebCalendar.thisDay=(new Date).getDate();a=WebCalendar.thisYear;c=WebCalendar.thisMonth;WebCalendar.iframe.meizzYearHead.innerText=a+"\u5e74";
WebCalendar.iframe.meizzYearMonth.innerText=parseInt(c,10)+"\u6708";WebCalendar.daysMonth[1]=0==a%4&&(a%100!=0||a%400==0)?29:28;for(var d=(new Date(a,c-1,1)).getDay(),e=c==1?WebCalendar.daysMonth[11]:WebCalendar.daysMonth[c-2],b=d-1;b>=0;b--)WebCalendar.day[b]=e+"/"+(parseInt(c,10)-1)+"/"+a,c==1&&(WebCalendar.day[b]=e+"/12/"+(parseInt(a,10)-1)),e--;for(b=1;b<=WebCalendar.daysMonth[c-1];b++)WebCalendar.day[b+d-1]=b+"/"+c+"/"+a;for(b=1;b<39-d-WebCalendar.daysMonth[c-1]+1;b++)WebCalendar.day[WebCalendar.daysMonth[c-
1]+d-1+b]=b+"/"+(parseInt(c,10)+1)+"/"+a,c==12&&(WebCalendar.day[WebCalendar.daysMonth[c-1]+d-1+b]=b+"/1/"+(parseInt(a,10)+1));for(b=0;b<39;b++){a=WebCalendar.day[b].split("/");WebCalendar.dayObj[b].innerText=a[0];WebCalendar.dayObj[b].title=a[2]+"-"+appendZero(a[1])+"-"+appendZero(a[0]);WebCalendar.dayObj[b].bgColor=WebCalendar.dayBgColor;WebCalendar.dayObj[b].style.color=WebCalendar.wordColor;if(b<10&&parseInt(WebCalendar.day[b],10)>20||b>27&&parseInt(WebCalendar.day[b],10)<12)WebCalendar.dayObj[b].style.color=
WebCalendar.wordDark;if(WebCalendar.inputDate==WebCalendar.day[b])WebCalendar.dayObj[b].bgColor=WebCalendar.darkColor,WebCalendar.dayObj[b].style.color=WebCalendar.lightColor;if(WebCalendar.day[b]==WebCalendar.today)WebCalendar.dayObj[b].bgColor=WebCalendar.todayColor,WebCalendar.dayObj[b].style.color=WebCalendar.lightColor}}
function returnDate(){if(WebCalendar.objExport){var a;a=arguments.length==0?WebCalendar.day[this.id.substr(8)].split("/"):arguments[0].split("/");var c=WebCalendar.format.match(/^(\w{4})(-|\/)(\w{1,2})\2(\w{1,2})$/);if(c==null)return alert("Date format is wrong!\r\n\r\nPlease define WebCalendar.format again!"),!1;var b=c[3].length==2||c[4].length==2;a=b?a[2]+c[2]+appendZero(a[1])+c[2]+appendZero(a[0]):a[2]+c[2]+a[1]+c[2]+a[0];if(WebCalendar.timeShow){var c=(new Date).getHours(),d=(new Date).getMinutes(),
e=(new Date).getSeconds();a+=b?" "+appendZero(c)+":"+appendZero(d)+":"+appendZero(e):" "+c+":"+d+":"+e}WebCalendar.objExport.value=a;hiddenCalendar()}}document.onclick=function(){WebCalendar.eventSrc!=window.event.srcElement&&hiddenCalendar()};
