typeof Prototype=="undefined"&&alert("forminvalid.js requires including prototype.js library");var InvalidForm=Class.create();
InvalidForm.prototype={initialize:function(){if(arguments!=null&&arguments[0]!=null)this.msg=arguments[0].evalJSON();this.msgPrefix="{text:'',textarea:'',radio:'',checkbox:'',select:'',email:'',number_length_rang:'',number_min_length_rang:'',number_max_length_rang:'',length_rang:'',min_length_rang:'',max_length_rang:'',exts:''}".evalJSON()},initAdvance:function(a,b){b=b||{enabledPrefix:!1,className:null,form:null};this.advanceMsg=Object.isString(a)?eval("("+a+")"):a;this.enablePrefix=b.enablePrefix?
!0:!1;this.className=b.className?b.className:"utrEm";this.form=b.form?b.form:null},setContainer:function(a,b){this.containerclassname=a;this.errclassname=b},setMsgPrefix:function(a){this.msgPrefix=a.evalJSON()},getMsgPrefix:function(a){return a=="text"||a=="password"?this.msgPrefix.text:a=="textarea"?this.msgPrefix.textarea:a=="radio"?this.msgPrefix.radio:a=="checkbox"?this.msgPrefix.checkbox:a=="select"||a=="file"?this.msgPrefix.select:a=="email"?this.msgPrefix.email:this.msgPrefix.text},getObject:function(a,
b){if(!b)b=this.form;var c,d;b||(b=document);if((c=a.indexOf("?"))>0&&parent.frames.length)b=parent.frames[a.substring(c+1)].document,a=a.substring(0,c);if(!(d=b[a])&&b.all)d=b.all[a];for(c=0;!d&&c<b.forms.length;c++)d=b.forms[c][a];for(c=0;!d&&b.layers&&c<b.layers.length;c++)d=this.getObject(a,b.layers[c].document);!d&&b.getElementById&&(d=b.getElementById(a));return d},_getFormType:function(a){if(a!=null)return a.length==null?a.type:a.length==0?a.type=="select-one"?"select":a.type:a[0].parentNode.type==
"select-one"?"select":a[0].type},getForm:function(a){typeof a=="string"&&(a=this.getObject(a));return a!=null?a.length==null?a:a.length==0?a:a[0].parentNode.type=="select-one"?a[0].parentNode:a[0]:null},getFormLength:function(a){typeof a=="string"&&(a=this.getObject(a));return a!=null&&a.length!=null&&a.length!=0?a.length:null},_length:function(a){return a.replace(/[^\x00-\xff]/g,"**").length},getWordLength:function(a){var b="",b="";if(a==null||a=="undefined")return 0;b=a.replace(/[\u3000-\u3002\u300a\u300b\u300e-\u3011\u2014\u2018\u2019\u201c\u201d\u2026\u203b\u25ce\uff01-\uff5e\uffe5]/gi,
" ");b=b.replace(/['"]/gi,"a");b=b.replace(/([^\x00-\xff])/gi," china ");b=b.replace(/\W/ig," ");b=b.replace(/\s+/ig," ");b=b.replace(/^ */,"").replace(/ *$/,"");return b.split(" ").length},_getKeyCode:function(a){var b;if(!a)a=window.event;if(a.keyCode)b=a.keyCode;else if(a.which)b=a.which;return b},checkFloat:function(a){a=this._getKeyCode(a);return(a<45||a>57||a==47)&&a!=45&&a!=9&&a!=8?!1:a==46&&obj.value.indexOf(".")>-1?!1:!0},checkInt:function(a){a=this._getKeyCode(a);return(a<48||a>57)&&a!=
45&&a!=9&&a!=8?!1:!0},isInt:function(a,b){if(!a)return!1;b==null&&(b="int");var c=/^[\+|\-|\d?](\d+)?$/;b=="-int"?c=/^[\-]\d+$/:b=="+int"&&(c=/^[\+|\d]\d*$/);if(!c.test(a))return!1;try{if(parseFloat(a)!=a)return!1}catch(d){return!1}return!0},isNumber:function(a,b){if(!a)return!1;b==null&&(b="number");var c=/^[\+|\-]\d+(\.\d+)?$/;b=="-number"?c=/^[\-]\d+(\.\d+)?$/:b=="+number"&&(c=/^[\+|\d]\d*(\.\d+)?$/);if(!c.test(a))return!1;try{if(parseFloat(a)!=a)return!1}catch(d){return!1}return!0},checkEmail:function(a){return RegExp(/^\w+((-\w+)|(\.\w+))*\@[A-Za-z0-9]+((\.|-)[A-Za-z0-9]+)*\.[A-Za-z0-9]+$/).test(a)},
checkSecondaryDomain:function(a){return/^[A-Z|a-z|0-9]+$/.test(a)},checkDomain:function(a){return/^[a-zA-Z0-9][-a-zA-Z0-9]{0,61}[a-zA-Z0-9](\.[a-zA-Z0-9][-a-zA-Z0-9]{0,61}[a-zA-Z0-9])+\.?$/.test(a)},checkContain:function(a,b){b=","+b.toUpperCase()+",";return a==""?-1:b.indexOf(","+a+",")==-1?0:1},removeContainItem:function(a,b){var c=b;c.indexOf(",")!=0&&(c=","+c);c.lastIndexOf(",")!=c.length-1&&(c+=",");c=c.replace(","+a+",","");c.indexOf(",")==0&&(c=c.substr(1,c.length-1));c.lastIndexOf(",")==c.length-
1&&(c=c.substr(0,c.length-1));return c},addContainItem:function(a,b){var c=b;c.lastIndexOf(",")!=c.length-1&&c!=""?c+=","+a:c==""?c=a:c+=a+",";return c},checkExt:function(a,b){return this.checkContain(this.getFileExt(a),b)==1},selectText:function(a){(a.type=="text"||a.type=="textarea")&&a.select()},getFullPath:function(a){var b=-1,b=a.lastIndexOf("\\");b==-1&&(b=a.lastIndexOf("/"));return b==-1?"":a.substring(0,b+1)},getFullName:function(a){var b=-1,b=a.lastIndexOf("\\");b==-1&&(b=a.lastIndexOf("/"));
return b==-1?a:a.substring(b+1)},getFileExt:function(a){a=a.substring(a.lastIndexOf(".")+1);return a.toUpperCase()},getFileSize:function(a){var b=this.getFullName(a).split("\\.")[0].split("_");return b.length!=3?[0,0]:(a=parseInt(isNaN(parseInt(b[1]))?0:b[1]),b=parseInt(isNaN(parseInt(b[2]))?0:b[2]),[a,b])},formatNumber:function(a,b,c){var d=0,f=0,e="1",d=""+a,a="",f=0,d=parseFloat(isNaN(parseFloat(d))?0:d);switch(!0){case b==0:d=Math.round(d);break;case b>0:for(a=0;a<b;a++)e+="0";f=parseInt(e);d=
Math.round(d*f)/f;c=="str"&&(a=d.toString(),a+=(a.indexOf(".")!=-1?"":".")+e.substr(1),f=a.indexOf(".")+1+b,d=a.substr(0,f))}return d},replaceText:function(a,b){for(var c=a,d="",f=0;f<b.length;f++)d="#"+f+"#",r=RegExp(d,"ig"),c=c.replace(r,b[f]);return c},clearSelected:function(a,b){if(a!=null)for(i=0;i<a.length;i++)a[i].checked=b!=-1&&b==i?!0:!1},selectedAll:function(a){if(a!=null)if(a.length==null)a.checked=!0;else for(i=0;i<a.length;i++)a[i].checked=!0},inverseSelected:function(a){if(a!=null)if(a.length==
null)a.checked=!a.checked;else for(i=0;i<a.length;i++)a[i].checked=!a[i].checked},getFocus:function(a){a!=null&&(a.length==null?a.focus():a.length==0?a.focus():a[0].parentNode.type=="select-one"?a[0].parentNode.focus():a[0].focus())},checkSelectedCustom:function(a,b){for(var c,d=0;d<b;d++)if(c=a.replace("{index}",d),c=$(c),c.checked)return!0;return!1},checkSelected:function(a,b){var c=!1,d=0;b==null&&(b=1);if(a!=null)if(a.length==null)a.checked==!0&&(c=!0);else for(i=0;i<a.length;i++)if(a[i].checked==
!0&&(d++,d>=b)){c=!0;break}return c},getSelectedValue:function(a){var b="";if(a!=null)if(a.length==null){if(a.checked==!0)b=a.value}else if(a.length==0)return a.value;else{if(a[0].parentNode.type=="select-one")return a[0].parentNode.value;for(i=0;i<a.length;i++)if(a[i].checked==!0)return a[i].value}return b},setSelectOption:function(a,b){var c=this._getFormType(a);if(c=="checkbox"||c=="radio")if(a.length)for(c=0;c<a.length;c++){if(a[c].value==b){a[c].checked=!0;break}}else{if(a.value==b)a.checked=
!0}else if(c=="select")for(c=0;c<a.options.length;c++)if(a.options[c].value==b){a.options[c].selected=!0;break}},operateSelect:function(a,b,c){var d,a=this.getObject(a);try{d=b.value,b.options[0].selected=!0}catch(f){d=b}if(a)if(a.length==null){if(!a.disabled)switch(b=this.getObject(c+"0"),d){case "all":a.checked=!0;$(b).addClassName("select");break;case "invert":a.checked=!a.checked;a.checked?$(b).addClassName("select"):$(b).removeClassName("select");break;case "none":a.checked=!1,$(b).removeClassName("select")}}else for(var e=
0;e<a.length;e++)if(!a[e].disabled)switch(b=this.getObject(c+e),d){case "all":a[e].checked=!0;$(b).addClassName("select");break;case "invert":a[e].checked=!a[e].checked;a[e].checked?$(b).addClassName("select"):$(b).removeClassName("select");break;case "none":a[e].checked=!1,$(b).removeClassName("select")}},Null2Space:function(a){return typeof a=="undefined"?"":a==null?"":a},TrimSep:function(a,b){var c=a.strip();c.indexOf(b)==0&&(c=c.substring(1));c.lastIndexOf(b)==c.length-1&&(c=c.substr(0,c.length-
1));return c},checkNull:function(a){return!(this._length(this.getObject(a).value.strip())>0)},initImmeInvalid:function(){for(var a=null,b=0;b<this.advanceMsg.length;b++){var c=this.advanceMsg[b];if(c==void 0||c==null||c==""){alert("FormInvalid.js warning::::\r\nyou input form element ["+(b+1)+"] setting was wrong, please check you invalid msg string.");break}if(a=this.getObject(this.advanceMsg[b].id)){var d=this._getFormType(a);if(d=="select"&&a.length>1)Event.observe(a,"change",this.immeInvalid.bind(this,
c).bindAsEventListener(this));else if(d=="select")Event.observe(a,"click",this.immeInvalid.bind(this,c).bindAsEventListener(this));else if(d=="checkbox"||d=="radio")if(a.length==null)Event.observe(a,"click",this.immeInvalid.bind(this,c).bindAsEventListener(this));else if(a.length==0)Event.observe(a,"click",this.immeInvalid.bind(this,c).bindAsEventListener(this));else for(d=0;d<a.length;d++)Event.observe(a[d],"click",this.immeInvalid.bind(this,c).bindAsEventListener(this));else Event.observe(a,"blur",
this.immeInvalid.bind(this,c).bindAsEventListener(this))}else{alert("FormInvalid.js warning::::\r\n id = ["+this.advanceMsg[b].id+"] not found object , please checked .");break}}},immeInvalid:function(a){for(var b=[],c=0;c<a.rules.length;c++)b[c]={type:a.rules[c].type,msg:a.rules[c].msg,notNull:a.rules[c].notNull,exts:a.rules[c].exts,minNumber:a.rules[c].minNumber,maxNumber:a.rules[c].maxNumber,lenType:a.rules[c].lenType,compareObjectId:a.rules[c].compareObjectId};a={id:a.id,rules:b,isfocus:!1,isalert:!1,
containerid:a.containerid,errmsgid:a.errmsgid};return this.InvalidCustom(a)?(this.focusErrorLine(a.id,"success","",a.containerid,a.errmsgid),!0):!1},start:function(){for(var a=0;a<this.advanceMsg.length;a++){var b=this.advanceMsg[a];if(b==void 0||b==null||b=="")return alert("FormInvalid.js warning::::\r\nyou input form element ["+(a+1)+"] setting was wrong, please check you invalid msg string."),!1;else if(!this.getObject(this.advanceMsg[a].id))return alert("FormInvalid.js warning::::\r\n id = ["+
this.advanceMsg[a].id+"] not found object , please checked ."),!1;if(!this.InvalidCustom(b))return!1}return!0},InvalidCustom:function(a){for(var b=0;b<a.rules.length;b++)if(!this.Invalid(a.id,a.rules[b].type,a.rules[b].msg,a.rules[b].notNull,a.rules[b].exts,a.rules[b].minNumber,a.rules[b].maxNumber,a.rules[b].lenType,a.isfocus,a.isalert,a.containerid,a.errmsgid,a.rules[b].compareObjectId))return b=a.rules[b].msg,this.enablePrefix&&(b=this.getMsgPrefix(this._getFormType(this.getObject(a.id)))+b),(a.isalert==
null||a.isalert=="undefined"||a.isalert)&&alert(b),(a.isfocus==null||a.isfocus=="undefined"||a.isfocus)&&this.getFocus(this.getObject(a.id)),this.focusErrorLine(a.id,"error",b,a.containerid,a.errmsgid),!1;return!0},Invalid:function(a,b,c,d,f,e,g,h,j,l,m,n,k){if(a=="null")return!0;if(e==null||e=="undefined")e=-1;if(g==null||g=="undefined")g=-1;if(d==null||d=="undefined")d=!1;if(b==null||b=="undefined")b="string";c=this.getObject(a);if(c==null||c==void 0)return alert("object not exist for id ["+a+"]"),
!1;j=this._getFormType(c);this.enablePrefix&&this.getMsgPrefix(j);a="";if(j=="file"||j=="password"||j=="text"||j=="textarea"||j=="select"){a=c.value.strip();if(j=="text"||j=="textarea")c.value=a;if(d&&a=="")return!0;if(b=="string"){if(b=this._length(a),h=="word"&&(b=this.getWordLength(a)),e!=-1&&g!=-1&&(b<e||b>g)||e!=-1&&g==-1&&b<e||e==-1&&g!=-1&&b>g||b==0)return!1}else if(b=="compare"&&k){e=this.getObject(k);if(e==null||e==void 0)return alert("compare object id not exist for id ["+k+"]"),!1;this._getFormType(e);
e=this.getForm(k).value;if(a!=e)return!1}else if(b=="int"||b=="+int"||b=="-int"||b=="number"||b=="+number"||b=="-number"){h=this.formatNumber(a);k=!1;if(b=="int"||b=="+int"||b=="-int")k=!this.isInt(a,b);else if(b=="number"||b=="+number"||b=="-number")k=!this.isNumber(a,b);if(e!=-1&&g!=-1&&(h<e||h>g)||e!=-1&&g==-1&&h<e||e==-1&&g!=-1&&h>g||a==""||k)return!1}else if(b=="email"){if(!this.checkEmail(a))return!1}else if(b=="secondarydomain"){if(e=/^[A-Z|a-z|0-9]+$/,!e.test(a))return!1}else if(b=="domain"){if(e=
/^[a-zA-Z0-9][-a-zA-Z0-9]{0,61}[a-zA-Z0-9](\.[a-zA-Z0-9][-a-zA-Z0-9]{0,61}[a-zA-Z0-9])+\.?$/,!e.test(a))return!1}else if(b=="file"){if(!this.checkExt(a,f))return!1}else if(b=="in"){if(this.checkContain(a,f))return!1}else if(b=="notin"&&!this.checkContain(a,f))return!1}else if(j=="checkbox"||j=="radio"){if(d&&!this.checkSelected(c))return!0;e==-1&&(e=1);if(!this.checkSelected(c,e))return!1}return!0},focusErrorLine:function(a,b,c,d,f){var e=this.containerclassname,g=this.errclassname;e||(e=".utr");
g||(g=".msgContent");var h=$(a+"_error_div");!h&&e&&(h=$(this.getForm(a)).up(e));d&&$(d)&&(h=$(d));h&&(b=="error"?h.addClassName(this.className):h.removeClassName(this.className));a=$(a+"_error_msg");!a&&g&&h&&(a=$(h).down(g));f&&$(f)&&(a=$(f));a&&(a.show(),b=="error"?(a.removeClassName("okMsg"),a.addClassName("errorMsg")):(a.removeClassName("errorMsg"),a.addClassName("okMsg")),(b=a.down(".msg"))&&b.update(c))}};var objInvalid=new InvalidForm;typeof msgPrefix!="undefined"&&objInvalid.setMsgPrefix(msgPrefix);
