var SmeWindows={windows:[],maxZIndex:4E3,maskWindow:null,register:function(a){if(this.maskWindow==null&&a.isMask)this.maskWindow=a;this.windows.length>0&&this.maskWindow!=null&&a.isMask==!0&&this.maskWindow.mask.setStyle({zIndex:a.zIndex-1});this.windows.push(a)},unregister:function(a){for(var b=null,d=null,e=-1,c=0;c<this.windows.length;c++){var f=this.windows[c];if(f==a){e=c;break}b==null&&f.isMask&&(b=f);f.isMask&&(d=f)}if(e!=-1)for(c=this.windows.length-1;c>e;c--)this.windows[c].closeWin();if(b!=
null)b.mask.setStyle({zIndex:d.zIndex-1}),this.maxZIndex=d.zIndex-1;this.windows.pop();if(this.windows.length==0)this.maskWindow=null,this.maxZIndex=4E3},checkMaskWindow:function(a){for(var b=null,d=0;d<this.windows.length;d++){var e=this.windows[d];if(e==a)break;b==null&&e.isMask&&(b=e)}return b!=null?!0:!1}},SmeWindow=Class.create();
SmeWindow.prototype={initialize:function(){this.options=Object.extend({id:null,className:null,title:"",width:500,height:400,url:null,parent:document.body,position:0,isMask:!1,isScroll:!1,winmode:"adv",textalign:"left",zIndex:SmeWindows.maxZIndex+5},arguments[0]||{});SmeWindows.maxZIndex+=5;this.id=this.options.id;this.title=this.options.title;this.width=this.options.width;this.height=this.options.height;this.url=this.options.url;this.parent=this.options.parent;this.position=this.options.position;
this.isMask=this.options.isMask;this.isScroll=this.options.isScroll;this.winmode=this.options.winmode;this.textalign=this.options.textalign;this.zIndex=this.options.zIndex;if(!this.zIndex)this.zIndex=SmeWindows.maxZIndex+5;if(!this.id)this.id="window_"+(new Date).getTime();$(this.id)&&alert("Window "+this.id+" is already registered in the DOM! Make sure you use setDestroyOnClose() or destroyOnClose: true in the constructor");this.className=this.options.className?(this.winmode=="adv"?"uWin":"uWinSimple")+
" "+this.options.className:this.winmode=="adv"?"uWin":"uWinSimple";this.winmode=="adv"&&this.title==""&&(this.className+=" uWinNoHx");if(this.url==null)this.url="";this.win=this._createWin();if(this.isMask)this.mask=this._createMask();this.content=$(this.id+"_content");this.content.style.textAlign=this.textalign;this.closeBtn=$(this.id+"_close_btn");this.eventCloseBtn=this.closeWin.bindAsEventListener(this);this.eventScroll=this.scrollWin.bindAsEventListener(this);this.eventResize=this.resizeWin.bindAsEventListener(this);
Event.observe(this.closeBtn,"click",this.eventCloseBtn);this.isScroll&&Event.observe(window,"scroll",this.eventScroll);Event.observe(window,"resize",this.eventResize)},_createWin:function(){var a=$(document.createElement("div"));a.writeAttribute({"class":this.className});a.hide();this.parent.insertBefore(a,this.parent.firstChild);var b=parseFloat(a.getStyle("border-top-width").replace("px","")),d=parseFloat(a.getStyle("padding-top").replace("px","")),e=parseFloat(a.getStyle("padding-bottom").replace("px",
"")),c=$(document.createElement("div"));c.writeAttribute({id:this.id,"class":this.className});var f=this.width,g=this.height;g-=d+e;this.winmode=="simple"&&(f-=b*2,g-=b*2);Element.setStyle(c,{width:f+"px",height:g+"px",zIndex:this.zIndex});b=this._createHead()+this._createBody()+this._createFooter();c.update(b);c.hide();a.remove();this.parent.insertBefore(c,this.parent.firstChild);return c},_createMask:function(){var a=$(document.createElement("div"));a.setAttribute("id",this.id+"_mask");a.className=
"maskDiv";a.style.zIndex=this.zIndex-1;this.parent.insertBefore(a,this.parent.firstChild);a.hide();return a},_createHead:function(){return this.winmode=="adv"?this.title==""?'<div class="uWinT"><i class="uWinTL"></i><i class="uWinTC"></i><i class="uWinTR"></i><span class="uWinToolBar"><a hideFocus class="closeBtn" href="javascript:void(0);" id="'+this.id+'_close_btn">Close</a></span></div>':'<div class="uWinH">\t\t\t\t\t <i class="uWinHL"></i><h3 class="uWinHC"><strong>'+this.title.escapeHTML()+'</strong><em class="shadow">'+
this.title.escapeHTML()+'</em></h3><i class="uWinHR"></i>\t\t\t\t\t <span class="uWinToolBar"><a href="javascript:void(0);" id="'+this.id+'_close_btn" class="closeBtn" hidefocus="true">Close</a></span>\t\t\t\t </div>':'<div class="uWinToolBar"><a href="javascript:void(0);" id="'+this.id+'_close_btn" class="closeBtn" hidefocus="true">Close</a></div>'},_createFooter:function(){return this.winmode=="adv"?'<div class="uWinB"><i class="uWinBL"></i><i class="uWinBC"></i><i class="uWinBR"></i></div>':""},
_createBody:function(){var a="";this.winmode=="adv"?(a+='<div class="uWinContent">',this.url==""?(a+='<div class="autoScroll" id="'+this.id+'_content">',a+="</div>"):a+='<iframe src="'+this.url+'" id="'+this.id+'_content" name="'+this.id+'_content" allowTransparency="true" frameborder="0"></iframe>',a+='<p class="uWinML"></p><p class="uWinMR"></p>'):(a+='<div class="uWinContent">',this.url==""?(a+='<div class="autoScroll" id="'+this.id+'_content">',a+="</div>"):a+='<iframe src="'+this.url+'" id="'+
this.id+'_content" name="'+this.id+'_content" allowTransparency="true" frameborder="0"></iframe>');a+="</div>";return a},setAjaxContent:function(a,b){b=b||{};this.setContent("");this.onComplete=b.onComplete;if(!this._onCompleteHandler)this._onCompleteHandler=this._setAjaxContent.bind(this);b.onComplete=this._onCompleteHandler;new Ajax.Request(a,b);b.onComplete=this.onComplete},_setAjaxContent:function(a){Element.update(this.getContent(),a.responseText);if(this.onComplete)this.onComplete(a);this.onComplete=
null},getContent:function(){return this.content},setContent:function(a){this.getContent().update(a)},show:function(a){if(this.isMask&&SmeWindows.maskWindow==null){var b=getPageSize();this.mask.setStyle({width:b[4]+20+"px",height:b[5]+20+"px",left:"0px",top:"0px"});this.parent.parentNode.style.overflow="hidden";hideSelectBoxes();hideFlash();this.mask.show()}SmeWindows.register(this);if(a)this.position=a;this.isShow=!0;this.scrollWin()},resizeWin:function(){this.scrollWin();if(SmeWindows.maskWindow!=
null){var a=getPageSize();SmeWindows.maskWindow.mask.setStyle({width:a[4]+20+"px",height:a[5]+20+"px",left:"0px",top:"0px"})}},scrollWin:function(){var a=getPageSize(),b=getPageScroll();if(!this.position)this.position=0;var d=0,e=0,c=0,f=0;this.position==0?(e=b[0]+(a[2]-this.width)/2+1,c=d=b[1]+(a[3]-this.height)/2,f=e):this.position==1?(d=b[1],c=d-this.height):this.position==2?(d=b[1],f=e=a[2]-this.width-19,c=d-this.height):this.position==3?(d=b[1]+a[3]-this.height,c=d+this.height):this.position==
4&&(e=a[2]-this.width-19,d=b[1]+a[3]-this.height,f=e,c=d+this.height);this.isShow&&this.win.setStyle({left:f+"px",top:c+"px"});this.win.show();new Effect.Move(this.win,{x:e,y:d,mode:"absolute"});this.isShow=!1},closeWin:function(){if(this.isMask){if(!SmeWindows.checkMaskWindow(this))this.parent.parentNode.style.overflow="",showSelectBoxes(),showFlash();this.mask.hide()}SmeWindows.unregister(this);Event.stopObserving(this.closeBtn,"click",this.eventCloseBtn);this.isScroll&&Event.stopObserving(window,
"scroll",this.eventScroll);Event.stopObserving(window,"resize",this.eventResize);if(this.url!="")this.content.src="about:blank";Element.remove(this.closeBtn);Element.remove(this.mask);Element.remove(this.win)}};
