addEvent(window,"load",sortables_init);var SORT_COLUMN_INDEX;function sortables_init(){if(document.getElementsByTagName){tbls=document.getElementsByTagName("table");for(ti=0;ti<tbls.length;ti++)thisTbl=tbls[ti],(" "+thisTbl.className+" ").indexOf("sortable")!=-1&&thisTbl.id&&ts_makeSortable(thisTbl)}}
function ts_makeSortable(a){if(a.rows&&a.rows.length>0)var c=a.rows[0];if(c)for(a=0;a<c.cells.length;a++){var e=c.cells[a],b=ts_getInnerText(e);e.innerHTML='<a href="#" class="sortheader" onclick="ts_resortTable(this, '+a+');return false;">'+b+'<span class="sortarrow">&nbsp;&nbsp;&nbsp;</span></a>'}}
function ts_getInnerText(a){if(typeof a=="string")return a;if(typeof a=="undefined")return a;if(a.innerText)return a.innerText;for(var c="",a=a.childNodes,e=a.length,b=0;b<e;b++)switch(a[b].nodeType){case 1:c+=ts_getInnerText(a[b]);break;case 3:c+=a[b].nodeValue}return c}
function ts_resortTable(a,c){for(var e,b=0;b<a.childNodes.length;b++)a.childNodes[b].tagName&&a.childNodes[b].tagName.toLowerCase()=="span"&&(e=a.childNodes[b]);ts_getInnerText(e);var d=a.parentNode,b=c||d.cellIndex,d=getParent(d,"TABLE");if(!(d.rows.length<=1)){var f=ts_getInnerText(d.rows[1].cells[b]);sortfn=ts_sort_caseinsensitive;f.match(/^\d\d[\/-]\d\d[\/-]\d\d\d\d$/)&&(sortfn=ts_sort_date);f.match(/^\d\d[\/-]\d\d[\/-]\d\d$/)&&(sortfn=ts_sort_date);f.match(/^[?]/)&&(sortfn=ts_sort_currency);
f.match(/^[\d\.]+$/)&&(sortfn=ts_sort_numeric);SORT_COLUMN_INDEX=b;b=[];for(i=0;i<d.rows[0].length;i++);for(j=1;j<d.rows.length;j++)b[j-1]=d.rows[j];b.sort(sortfn);e.getAttribute("sortdir")=="down"?(ARROW="&nbsp;&nbsp;&uarr;",b.reverse(),e.setAttribute("sortdir","up")):(ARROW="&nbsp;&nbsp;&darr;",e.setAttribute("sortdir","down"));for(i=0;i<b.length;i++)(!b[i].className||b[i].className&&b[i].className.indexOf("sortbottom")==-1)&&d.tBodies[0].appendChild(b[i]);for(i=0;i<b.length;i++)b[i].className&&
b[i].className.indexOf("sortbottom")!=-1&&d.tBodies[0].appendChild(b[i]);d=document.getElementsByTagName("span");for(b=0;b<d.length;b++)if(d[b].className=="sortarrow"&&getParent(d[b],"table")==getParent(a,"table"))d[b].innerHTML="&nbsp;&nbsp;&nbsp;";e.innerHTML=ARROW}}function getParent(a,c){return a==null?null:a.nodeType==1&&a.tagName.toLowerCase()==c.toLowerCase()?a:getParent(a.parentNode,c)}
function ts_sort_date(a,c){aa=ts_getInnerText(a.cells[SORT_COLUMN_INDEX]);bb=ts_getInnerText(c.cells[SORT_COLUMN_INDEX]);aa.length==10?dt1=aa.substr(6,4)+aa.substr(3,2)+aa.substr(0,2):(yr=aa.substr(6,2),yr=parseInt(yr)<50?"20"+yr:"19"+yr,dt1=yr+aa.substr(3,2)+aa.substr(0,2));bb.length==10?dt2=bb.substr(6,4)+bb.substr(3,2)+bb.substr(0,2):(yr=bb.substr(6,2),yr=parseInt(yr)<50?"20"+yr:"19"+yr,dt2=yr+bb.substr(3,2)+bb.substr(0,2));return dt1==dt2?0:dt1<dt2?-1:1}
function ts_sort_currency(a,c){aa=ts_getInnerText(a.cells[SORT_COLUMN_INDEX]).replace(/[^0-9.]/g,"");bb=ts_getInnerText(c.cells[SORT_COLUMN_INDEX]).replace(/[^0-9.]/g,"");return parseFloat(aa)-parseFloat(bb)}function ts_sort_numeric(a,c){aa=parseFloat(ts_getInnerText(a.cells[SORT_COLUMN_INDEX]));isNaN(aa)&&(aa=0);bb=parseFloat(ts_getInnerText(c.cells[SORT_COLUMN_INDEX]));isNaN(bb)&&(bb=0);return aa-bb}
function ts_sort_caseinsensitive(a,c){aa=ts_getInnerText(a.cells[SORT_COLUMN_INDEX]).toLowerCase();bb=ts_getInnerText(c.cells[SORT_COLUMN_INDEX]).toLowerCase();return aa==bb?0:aa<bb?-1:1}function ts_sort_default(a,c){aa=ts_getInnerText(a.cells[SORT_COLUMN_INDEX]);bb=ts_getInnerText(c.cells[SORT_COLUMN_INDEX]);return aa==bb?0:aa<bb?-1:1}
function addEvent(a,c,e,b){if(a.addEventListener)return a.addEventListener(c,e,b),!0;else if(a.attachEvent)return a.attachEvent("on"+c,e);else alert("Handler could not be removed")};
